export const Errors = {
  INVALID_INPUT: "INVALID INPUT",
  INVALID_WITNESS: "INVALID WITNESS",
  INVALID_VOUT: "INVALID VOUT",
  PUBKEY_NOT_FOUND: "PUBKEY NOT FOUND",
  INVALID_PREVOUT: "INVALID PREVOUT",
};
