export const ERRORS = {
  MISMATCHED_IF_ELSE: "MISMATCHED IF_ELSE",
  OP_ENDIF_WITHOUT_OP_IF: "OP_ENDIF_WITHOUT_OP_IF",
  OP_ELSE_WITHOUT_OP_IF: "OP_ELSE_WITHOUT_OP_IF",
  VERIFY: "TOP VALUE IS FALSE",
  STACK_EMPTY: "STACK IS EMPTY",
};
