export const ERRORS = {
  MISMATCHED_IF_ELSE: "MISMATCHED IF_ELSE",
  OP_ENDIF_WITHOUT_OP_IF: "OP_ENDIF_WITHOUT_OP_IF",
  OP_ELSE_WITHOUT_OP_IF: "OP_ELSE_WITHOUT_OP_IF",
  VERIFY: "TOP VALUE IS FALSE",
  STACK_EMPTY: "STACK IS EMPTY",
  MULTISIG: {
    INVALID_N_VALUE: "INVALID N VALUE",
    INVALID_M_VALUE: "INVALID M VALUE",
    M_GREATER_THAN_N: "M GREATER THAN N",
  },
  INVALID_TX: "INVALID TRANSACTION",
};
